export default [
  {
    name: 'Teresa',
    subject: 'Pick up Sandy from soccer at 6',
    preview: 'And pick up milk on your way home hunny. ',
    attach: true,
    favorite: false,
    time: '04:23 PM',
    unread: true,
  },
  {
    name: 'Bryon Baker',
    subject: 'Automated Reporting',
    preview: 'Hey Pete, the automated reporting from CannInventory to OMMA works GREAT!',
    attach: false,
    favorite: true,
    time: '09:54 AM',
    unread: false,
  },
  {
    name: 'National Bank of Canada',
    subject: 'Statement for April 2019.',
    preview: 'Please see downloadable attachment for your recent statement. ',
    attach: true,
    favorite: true,
    time: '8:54 AM',
    unread: true,
  },
  {
    name: 'Charlie Schneider',
    subject: 'Schedule for next week. ',
    preview: 'Hey Pete, I need to get next Thursday off to get my vehicle serviced. ',
    attach: false,
    favorite: false,
    time: '11:54 AM',
    unread: false,
  },
  {
    name: 'Sean Shafer',
    subject: 'Great read on new reporting guidelines in Michigan.',
    preview: 'Hey Pete, check out this new law going through in Michigan.',
    attach: false,
    favorite: false,
    time: 'July 10 ',
    unread: false,
  },
];
